{"cells":[{"cell_type":"markdown","metadata":{"id":"7inZ2QqrkgzV"},"source":["# Обработка исключений"]},{"cell_type":"markdown","metadata":{"id":"CwcfXWPSkgzZ"},"source":["Исключения (exceptions) - ещё один тип данных в `Python`.\n","Исключения необходимы для того, чтобы сообщать программисту об ошибках."]},{"cell_type":"markdown","metadata":{"id":"94a7W4Ydkgza"},"source":["#### Список основных встроенных исключений:\n","\n","* Exception – то, на чем фактически строятся все остальные ошибки;\n","\n","* AttributeError – возникает, когда ссылка атрибута или присвоение не могут быть выполнены;\n","\n","* IOError – возникает в том случае, когда операция I/O (такая как оператор вывода, встроенная функция open() или метод объекта-файла) не может быть выполнена, по связанной с I/O причине: «файл не найден», «диск заполнен» и т.п.;\n","\n","* ImportError – возникает, когда оператор import не может найти определение модуля, или когда оператор не может найти имя файла, который должен быть импортирован;\n","\n","* IndexError – возникает, когда индекс последовательности находится вне допустимого диапазона;\n","\n","* KeyError – возникает, когда ключ сопоставления (dictionary key) не найден в наборе существующих ключей;\n","* KeyboardInterrupt – возникает, когда пользователь нажимает клавишу прерывания(обычно Delete или Ctrl+C);\n","* NameError – возникает, когда локальное или глобальное имя не найдено;\n","* OSError – возникает, когда функция получает связанную с системой ошибку;\n","* SyntaxError – возникает, когда синтаксическая ошибка встречается синтаксическим анализатором;\n","* TypeError – возникает, когда операция или функция применяется к объекту несоответствующего типа. Связанное значение представляет собой строку, в которой приводятся подробные сведения о несоответствии типов;\n","* ValueError – возникает, когда встроенная операция или функция получают аргумент, тип которого правильный, но неправильно значение, и ситуация не может быть описана более точно, как при возникновении IndexError;\n","* ZeroDivisionError – возникает, когда второй аргумент операции division или modulo равен нулю."]},{"cell_type":"markdown","metadata":{"id":"6b_STSWpkgzc"},"source":["Самый простейший пример исключения - деление на ноль:"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"q0q_BYfTkgzd","outputId":"e2309258-5835-41ae-bd30-2af06afaec37","colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"status":"error","timestamp":1736725067422,"user_tz":-180,"elapsed":333,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-bbe761e74a70>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m100\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["100/0"]},{"cell_type":"markdown","metadata":{"id":"nu5UYHGSkgzf"},"source":["Для обработки исключений используется конструкция `try - except`.\n","\n","В блоке `try` мы выполняем инструкцию, которая может породить исключение, а в блоке `except` мы перехватываем ошибки. При этом перехватываются как само исключение, так и его потомки.\n","\n","Первый пример применения этой конструкции:"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"5h-4zJfekgzf","outputId":"e514621c-28be-46ce-e972-c4321e9b635c","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725099906,"user_tz":-180,"elapsed":458,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["1\n"]}],"source":["try:\n","    k = 1 / 0\n","except ZeroDivisionError:\n","    k = 0\n","print(k)"]},{"cell_type":"markdown","metadata":{"id":"oTwUlPAwkgzg"},"source":["### \"Голое\" исключение"]},{"cell_type":"markdown","metadata":{"id":"hKvIP-Nukgzg"},"source":["Также возможна инструкция except без аргументов, будут найдены вообще все исключения. Причина, по которой так делать не рекомендуется, заключается в том, что вы не узнаете, что именно за исключение вы выловите."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"bj2JvuWJkgzh","outputId":"a1758c22-f811-4cff-e3f2-419bed5b7e1c"},"outputs":[{"name":"stdout","output_type":"stream","text":["Произошла ошибка!\n"]}],"source":["try:\n","    1 / 0\n","except:\n","    print(\"Произошла ошибка!\")"]},{"cell_type":"markdown","metadata":{"id":"lmYvTQJ5kgzi"},"source":["\n","\n","Вы также можете выявить несколько ошибок за раз при помощи одного оператора. Для этого существует несколько различных способов.\n","\n","Самый стандартный способ выявить несколько исключений:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"uAbzd6TSkgzi","colab":{"base_uri":"https://localhost:8080/","height":106},"executionInfo":{"status":"error","timestamp":1736725163705,"user_tz":-180,"elapsed":247,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}},"outputId":"11cc105c-feb4-4507-9fd6-6ff61952ce0e"},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-6-4cfc09340e2e>, line 1)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-6-4cfc09340e2e>\"\u001b[0;36m, line \u001b[0;32m1\u001b[0m\n\u001b[0;31m    my_dict = {\"a\":1, \"b\":2, \"c\":?////3}\u001b[0m\n\u001b[0m                                 ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"]}],"source":["my_dict = {\"a\":1, \"b\":2, \"c\":3}\n","\n","try:\n","    value = my_dict[\"d\"]\n","except IndexError:\n","    print(\"Такого индекса не существует!\")\n","except KeyError:\n","    print(\"Этого ключа нет в словаре!\")\n","except:\n","    print(\"Произошла еще одна ошибка!\")"]},{"cell_type":"markdown","metadata":{"id":"Hgyt2C4Wkgzj"},"source":["Второй способ выявления нескольких исключений:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vaMliVewkgzj"},"outputs":[],"source":["try:\n","    value = my_dict[\"d\"]\n","except (IndexError, KeyError):\n","    print(\"Произошла ошибка IndexError или KeyError!\")"]},{"cell_type":"markdown","metadata":{"id":"Ry4wPeTtkgzj"},"source":["В данном примере мы помещаем ошибки, которые мы хотим выявить, внутри круглых скобок. Проблема данного метода в том, что трудно сказать какая именно ошибка произошла, так что предыдущий пример рекомендован больше чем этот. Зачастую, когда происходит ошибка, вам нужно уведомить пользователя, при помощи сообщения."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"owf7Lb5Jkgzm","outputId":"807730a4-9cd1-4daf-a408-74a8e7c0ad91","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725242203,"user_tz":-180,"elapsed":3387,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["5\n","division by zero\n"]}],"source":["try:\n","    k = int(input())\n","    x = k / 0\n","except Exception as err:\n","    print(err)"]},{"cell_type":"markdown","metadata":{"id":"U46oOBDukgzp"},"source":["### Блок *finally* в Python\n","\n","После последнего блока except можно добавить блок `finally`. Он исполняет инструкции при любых условиях."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"g6RSqwAQkgzv","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725275784,"user_tz":-180,"elapsed":305,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}},"outputId":"492cb631-98ae-4684-817d-5a2e85aa7eef"},"outputs":[{"output_type":"stream","name":"stdout","text":["Этого ключа нет в словаре!\n","Выражение выполнено!\n"]}],"source":["try:\n","    value = my_dict[\"d\"]\n","except KeyError:\n","    print(\"Этого ключа нет в словаре!\")\n","finally:\n","    print(\"Выражение выполнено!\")"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"u86hPVAlkgzv","outputId":"f77868f0-abcf-47fa-dffd-1518399c0f6f","colab":{"base_uri":"https://localhost:8080/","height":228},"executionInfo":{"status":"error","timestamp":1736725288215,"user_tz":-180,"elapsed":341,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Это будет напечатано в любом случае.\n"]},{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-10-6841dffa7bae>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;32mexcept\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Это ошибка значения\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["try:\n","    print(1/0)\n","except ValueError:\n","    print(\"Это ошибка значения\")\n","finally:\n","    print(\"Это будет напечатано в любом случае.\")"]},{"cell_type":"markdown","metadata":{"id":"b2tzkrzpkgzw"},"source":["### Пункт *else* в `try/except`"]},{"cell_type":"markdown","metadata":{"id":"IQs3fj1Bkgzw"},"source":["Он работает только в том случае, если в вашем коде нет ошибки. Рассмотрим пример:"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"t2kKlnDNkgzx","outputId":"4c896da1-0884-44c1-f7da-95d9848f742d","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725522332,"user_tz":-180,"elapsed":806,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Никакой ошибки не произошло!\n"]}],"source":["my_dict = {\"a\":1, \"b\":2, \"c\":3}\n","\n","try:\n","    value = my_dict[\"a\"]\n","except KeyError:\n","    print(\"Этого ключа нет в словаре!\")\n","else:\n","    print(\"Никакой ошибки не произошло!\")"]},{"cell_type":"markdown","metadata":{"id":"Vdyn7_eOkgzx"},"source":["В операторе `try/except` мы открываем доступ к существующему ключу. Это работает, так что ошибка `KeyError` не возникает. Так как ошибки нет, `else` работает, и надпись “Никакой ошибки не произошло!” появляется на экране.\n","\n","Теперь добавим оператор `finally`:"]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"kJqx3R4Rkgzy","outputId":"c15c6a9a-8aab-4a8a-dd99-5d21235dfd54","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725543031,"user_tz":-180,"elapsed":295,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Никакой ошибки не произошло!\n","Выражение работает!\n"]}],"source":["try:\n","    value = my_dict[\"a\"]\n","except KeyError:\n","    print(\"Этого ключа нет в словаре!\")\n","else:\n","    print(\"Никакой ошибки не произошло!\")\n","finally:\n","    print(\"Выражение работает!\")"]},{"cell_type":"markdown","metadata":{"id":"AKkBdawSkgzy"},"source":["Единственное полезное применение оператора `else`, когда вы хотите запустить вторую часть кода, в которой может быть ошибка. Конечно, если ошибка возникает в `else`, то она не будет поймана."]},{"cell_type":"markdown","metadata":{"id":"EgAXLXCnkgzz"},"source":["Обработка исключений в цикле. В данном примере у пользователя будут запрашиваться числа до тех пор, пока не будут введены числа неравные нулю или выполнение не будет прервано (обычно Ctrl-C)."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"4qW1uU2Ekgzz","outputId":"3e693ae2-6039-49ad-9d11-89504c4aa059","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725628503,"user_tz":-180,"elapsed":23725,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Введите число: вц\n","Введите второе число: свыс\n","Поддерживаются только числа\n","Введите число: 3\n","Введите второе число: 0\n","На ноль делить нельзя\n","Введите число: 4\n","Введите второе число: 5\n","0.8\n"]}],"source":["while True:\n","    a = input(\"Введите число: \")\n","    b = input(\"Введите второе число: \")\n","    try:\n","        result = int(a)/int(b)\n","    except ValueError:\n","        print(\"Поддерживаются только числа\")\n","    except ZeroDivisionError:\n","        print(\"На ноль делить нельзя\")\n","    else:\n","        print(result)\n","        break"]},{"cell_type":"markdown","metadata":{"id":"F0d29DMmkgz2"},"source":["Если же цикл находится внутри обработчика исключений, то его выполнение завершится при первой произошедшей ошибке. В данном примере у пользователя будут запрашиваться числа и будет выводится их частное до тех пор, пока не будут введены некорретные значения."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"NeQdxwFYkgz3","outputId":"95f453cb-26d1-4eee-f35e-7564229e19b3","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1736725698345,"user_tz":-180,"elapsed":23266,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Введите число: 5\n","Введите второе число: 5\n","1.0\n","Введите число: в\n","Введите второе число: в\n","Поддерживаются только числа\n"]}],"source":["try:\n","    while True:\n","        a = input(\"Введите число: \")\n","        b = input(\"Введите второе число: \")\n","        result = int(a)/int(b)\n","        print(result)\n","except ValueError:\n","    print(\"Поддерживаются только числа\")\n","except ZeroDivisionError:\n","    print(\"На ноль делить нельзя\")"]},{"cell_type":"markdown","metadata":{"id":"7JsnahHkkgz3"},"source":["Исключение, произошедшее в методе, вызов которого находится в обработчике исключений, так же будет обработано."]},{"cell_type":"code","execution_count":null,"metadata":{"tags":[],"id":"OMmxA8Y4kgz3","outputId":"7a1b51e8-7076-4e02-e89c-475d9523c58b"},"outputs":[{"name":"stdin","output_type":"stream","text":["Введите число:  7\n","Введите второе число:  0\n"]},{"name":"stdout","output_type":"stream","text":["На ноль делить нельзя\n"]}],"source":["def division(x,y):\n","    return int(a)/int(b)\n","\n","try:\n","    a = input(\"Введите число: \")\n","    b = input(\"Введите второе число: \")\n","    print(division(a,b))\n","except ZeroDivisionError:\n","    print(\"На ноль делить нельзя\")"]},{"cell_type":"code","execution_count":6,"metadata":{"id":"XV_4h5u9kgz4","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1740523913894,"user_tz":-180,"elapsed":3569,"user":{"displayName":"Gendelfwhite","userId":"01103463166359463338"}},"outputId":"81db120a-4308-4360-94cb-b7e8888d5370"},"outputs":[{"output_type":"stream","name":"stdout","text":["18 11 12\n","True\n"]}],"source":["a, b, c = map(int, input().split())\n","print(a + b > c and a + c > b and c + b > a)"]}],"metadata":{"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.5"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}